config/routes.rb
Rails.application.routes.draw do
	devise_for :podcasts

    resources :podcasts, only: [ :index, :show ] do
    	resources :episodes
    end

    authenticated :podcast do
    	root 'podcasts#dashboard', as: "authenticated_root"
    end

    root to: 'welcome#index'
end

app/models/episode.rb
class Episode < ActiveRecord::Base
	belongs_to :podcast

  	has_attached_file :thumbnail, styles: { large: "1000x1000#", medium: "500x500#" }
  	validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\Z/

  	has_attached_file :mp3
  	validates_attachment_content_type :mp3, content_type: [ "audio/mpeg", "audio/mp3" ]
  	validates_attachment_file_name :mp3, matches: [ /mp3\Z/ ]
end

app/models/podcast.rb
class Podcast < ActiveRecord::Base
	# Include default devise modules. Others available are:
	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable

    has_many :episodes

	has_attached_file :thumbnail, styles: { large: "1000x1000#", medium: "500x500#" }
  	validates_attachment_content_type :thumbnail, content_type: /\Aimage\/.*\Z/    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :password_confirmation, :title, :thumbnail) }
  	devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation,
  		:current_password, :title, :description, :itunes, :stitcher, :podbay, :thumbnail) }
  end
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController
	before_action :authenticate_podcast!, except: [ :show ]
	before_action :require_permission, except: [ :show ]
	before_action :find_podcast
	before_action :find_episode, only: [ :show, :edit, :update, :destroy ]

	def new
		@episode = @podcast.episodes.new
	end

	def create
		@episode = @podcast.episodes.new episode_params

		if @episode.save
			redirect_to podcast_episode_path(@podcast, @episode)
		else
			render 'new'
		end
	end

	def show
		@episodes = @podcast.episodes.order("created_at desc").limit(6).reject{ |e| e.id == @episode.id }
	end

	def edit
	end

	def update
		if @episode.update episode_params
			redirect_to podcast_episode_path(@podcast, @episode), notice: "Episode was successfully updated!"
		else
			render 'edit'
		end
	end

	def destroy
		@episode.destroy
		redirect_to root_path
	end

	private

	def find_podcast
		@podcast = Podcast.find(params[:podcast_id])
	end

	def find_episode
		@episode = Episode.find(params[:id])
	end

	def episode_params
		params.require(:episode).permit(:title, :description, :thumbnail, :mp3)
	end

	def require_permission
		@podcast = Podcast.find(params[:podcast_id])
		if current_podcast != @podcast
			redirect_to root_path, notice: "Sorry, you're not allowed to view that page."
		end
	end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
	before_action :find_podcast, only: [ :show, :dashboard ]
	before_action :find_episodes, only: [ :show, :dashboard ]

	def index
		@podcasts = Podcast.all.order("created_at desc").paginate(page: params[:page], per_page: 12)
	end

	def show
	end

	def dashboard
	end

	private

	def find_podcast
		if params[:id].nil?
			@podcast = current_podcast
		else
			@podcast = Podcast.find(params[:id])
		end
	end

	def find_episodes
		@episodes = @podcast.episodes.order("created_at desc").paginate(page: params[:page], per_page: 5)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/episodes/_form.html.erb
<%= form_for ([ @podcast, @episode ]) do |f| %>
	<% @episode.errors.full_messages.each do |msg| %>
		<div><%= msg %></div>
	<% end %>
	<div class="field">
		<%= f.label :title %>
		<%= f.text_field :title %>
	</div>
	
	<div class="field">
		<%= f.label :description %>
		<%= f.text_area :description %>
	</div>

	<div class="field">
		<%= f.label :thumbnail %>
		<%= f.file_field :thumbnail %>
	</div>

	<div class="field">
		<%= f.label :mp3 %>
		<%= f.file_field :mp3 %>
	</div>

	<%= f.submit class: "button button_highlight button_block" %>
<% end %>

app/views/episodes/_mp3.html.erb
<% unless @episode.mp3.blank? %>
	<div id="audio_container">
		<audio controls>
			<source src="<%= @episode.mp3.url %>">
		</audio>
	</div>
<% end %>

app/views/episodes/edit.html.erb
<div id="podcast_show">
    <div id="show_banner">
        <div class="wrapper_skinny">
            <h1><%= @podcast.title %> Dashboard</h1>
        </div>
    </div>

    <div id="links">
        <div class="wrapper_skinny">
            <ul>
                <li><%= link_to "Episodes", root_path %></li>
                <li><%= link_to "New Episode", new_podcast_episode_path(@podcast) %></li>

                <li><%= link_to "Account Settings", edit_podcast_registration_path %></li>
                <li><%= link_to "View Podcast", @podcast %></li>
            </ul>
        </div>
    </div>

    <div id="form">
        <div class="wrapper_skinny">

        <h1>Edit Episode</h1>

        <%= render 'form' %>
    </div>
</div>

app/views/episodes/new.html.erb
<div id="podcast_show">
    <div id="show_banner">
        <div class="wrapper_skinny">
            <h1><%= @podcast.title %> Dashboard</h1>
        </div>
    </div>

    <div id="links">
        <div class="wrapper_skinny">
            <ul>
                <li><%= link_to "Episodes", root_path %></li>
                <li><%= link_to "New Episode", new_podcast_episode_path(@podcast), class: "current" %></li>

                <li><%= link_to "Account Settings", edit_podcast_registration_path %></li>
                <li><%= link_to "View Podcast", @podcast %></li>
            </ul>
        </div>
    </div>

	<div id="form">
	    <div class="wrapper_skinny">

		<h1>New Episode</h1>

		<%= render 'form' %>
	</div>
</div>

app/views/episodes/show.html.erb
<div id="podcast_show">
	<div id="show_banner">
		<div class="wrapper_skinny">
			<h1><%= @podcast.title %></h1>
			<p class="description"><%= @podcast.description %></p>
			<% unless @podcast.itunes.blank? %>
				<a href="<%= @podcast.itunes %>" class="subscribe_link">iTunes</a>
			<% end %>
			<% unless @podcast.stitcher.blank? %>
				<a href="<%= @podcast.stitcher %>" class="subscribe_link">Stitcher</a>
			<% end %>
			<% unless @podcast.podbay.blank? %>
				<a href="<%= @podcast.podbay %>" class="subscribe_link">PodBay</a>
			<% end %>
		</div>
	</div>

	<div id="breadcrumb">
		<%= link_to podcasts_path do %>
			All Podcasts
			<span>/</span>
			<%= link_to @podcast.title, @podcast %>
			<span>/</span>
			<%= @episode.title %>
		<% end %>
	</div>

	<div id="episode_content">
		<div class="wrapper_skinny">
			<%= image_tag @episode.thumbnail.url(:medium), class: "current_episode_thumbnail" %>
			<h2><%= @episode.title %></h2>
			<p class="description"><%= @episode.description %></p>
			<%= render 'mp3' %>
		</div>
	</div>

	<div id="episodes">
		<div class="wrapper_skinny">
			<ul class="clearfix">
				<% @episodes.each do |episode| %>
					<li class="clearfix">
						<div class="episode_thumbnail">
							<%= link_to podcast_episode_path(@podcast, episode) do %>
								<%= image_tag episode.thumbnail.url(:medium) %>
							<% end %>
						</div>
						<div class="episode_overview">
							<h2><%= link_to episode.title, podcast_episode_path(@podcast, episode) %></h2>
							<p class="description"><%= truncate(episode.description, length: 160) %></p>
						</div>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

app/views/layouts/_header.html.erb
<header id="main_header" class="clearfix">
	<div class="wrapper_wide">
		<%= link_to "Podcast.fm", root_path, id: "logo" %>
		<nav>
			<ul>
				<% unless podcast_signed_in? %>
					<li><%= link_to "Explore", podcasts_path %></li>
					<li><%= link_to "Sign In", new_podcast_session_path %></li>
					<li><%= link_to "Create a Podcast", new_podcast_registration_path %></li>
				<% else %>
					<li><%= link_to "Dashboard", root_path %></li>
					<li><%= link_to "Explore", podcasts_path %></li>
					<li><%= link_to "Sign Out", destroy_podcast_session_path, method: :delete %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PodcastFm</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if alert %>
	<div id="notice_wrapper">
		<p class="alert"><%= alert %></p>
	</div>
<% elsif notice %>
	<div id="notice_wrapper">
		<p class="notice"><%= notice %></p>
	</div>
<% end %>


<% unless current_page?(root_path) %>
	<%= render 'layouts/header' %>
<% end %>

<%= yield %>

<script>
	$(document).ready(function() {
		setTimeout(function() {
			$('#notice_wrapper').fadeOut("slow", function() {
					this.remove();
			});
		}, 4500);
	});
</script>

</body>
</html>

app/views/podcasts/dashboard.html.erb
<header id="main_header" class="clearfix">
	<div class="wrapper_wide">
		<%= link_to "Podcast.fm", root_path, id: "logo" %>
		<nav>
			<ul>
				<% unless podcast_signed_in? %>
					<li><%= link_to "Explore", podcasts_path %></li>
					<li><%= link_to "Sign In", new_podcast_session_path %></li>
					<li><%= link_to "Create a Podcast", new_podcast_registration_path %></li>
				<% else %>
					<li><%= link_to "Dashboard", root_path %></li>
					<li><%= link_to "Explore", podcasts_path %></li>
					<li><%= link_to "Sign Out", destroy_podcast_session_path, method: :delete %></li>
				<% end %>
			</ul>
		</nav>
	</div>
</header>

<div id="podcast_show">
	<div id="show_banner">
		<div class="wrapper_skinny">
			<h1><%= @podcast.title %> Dashboard</h1>
		</div>
	</div>

	<div id="links">
		<div class="wrapper_skinny">
			<ul>
				<li><%= link_to "Episodes", root_path, class: "current" %></li>
				<li><%= link_to "New Episode", new_podcast_episode_path(@podcast) %></li>
				<li><%= link_to "Account Settings", edit_podcast_registration_path %></li>
				<li><%= link_to "View Podcast", @podcast %></li>
			</ul>
		</div>
	</div>

	<div id="episodes">
		<div class="wrapper_skinny">
			<ul class="clearfix">
				<% @episodes.each do |episode| %>
					<li class="clearfix">
						<div class="episode_thumbnail">
							<%= link_to podcast_episode_path(@podcast, episode) do %>
								<%= image_tag episode.thumbnail.url(:medium) %>
							<% end %>
						</div>
						<div class="episode_overview">
							<h2><%= link_to episode.title, podcast_episode_path(@podcast, episode) %></h2>
							<p class="description"><%= episode.description %></p>
							<div class="authorized_links">
								<%= link_to "Edit", edit_podcast_episode_path(@podcast, episode) %>
								<%= link_to "Delete", podcast_episode_path(@podcast, episode), method: :delete, data: { confirm: "Are you sure?" } %>
							</div>
						</div>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

<%= will_paginate @episodes %>

app/views/podcasts/index.html.erb
<div id="banner" class="podcasts_banner">
	<h1>Discover your new favorite podcast.</h1>
</div>

<div id="podcasts" class="clearfix">
	<div class="wrapper">
		<ul>
			<% @podcasts.each do |podcast| %>
				<%= link_to podcast do %>
					<li>
						<%= image_tag podcast.thumbnail.url(:medium) %>
						<div class="podcast_overview">
							<h2><%= podcast.title %></h2>
							<p class="episode_count"><%= pluralize(podcast.episodes.count, "Episode") %></p>
						</div>
					</li>
				<% end %>
			<% end %>
		</ul>
	</div>
</div>

<%= will_paginate @podcasts %>

app/views/podcasts/show.html.erb
<div id="podcast_show">
	<div id="show_banner">
		<div class="wrapper_skinny">
			<h1><%= @podcast.title %></h1>
			<p class="description"><%= @podcast.description %></p>
			<% unless @podcast.itunes.blank? %>
				<a href="<%= @podcast.itunes %>" class="subscribe_link">iTunes</a>
			<% end %>
			<% unless @podcast.stitcher.blank? %>
				<a href="<%= @podcast.stitcher %>" class="subscribe_link">Stitcher</a>
			<% end %>
			<% unless @podcast.podbay.blank? %>
				<a href="<%= @podcast.podbay %>" class="subscribe_link">PodBay</a>
			<% end %>
		</div>
	</div>

	<div id="breadcrumb">
		<%= link_to podcasts_path do %>
			All Podcasts
			<span>/</span>
			<%= link_to @podcast.title, @podcast %>
		<% end %>
	</div>

	<div id="episodes">
		<div class="wrapper_skinny">
			<ul class="clearfix">
				<% @episodes.each do |episode| %>
					<li class="clearfix">
						<div class="episode_thumbnail">
							<%= link_to podcast_episode_path(@podcast, episode) do %>
								<%= image_tag episode.thumbnail.url(:medium) %>
							<% end %>
						</div>
						<div class="episode_overview">
							<h2><%= link_to episode.title, podcast_episode_path(@podcast, episode) %></h2>
							<p class="description"><%= truncate(episode.description, length: 160) %></p>
						</div>
					</li>
				<% end %>
			</ul>
		</div>
	</div>
</div>

<%= will_paginate @episodes %>

app/views/welcome/index.html.erb
<div id="background">
	<header class="clearfix">
		<div class="wrapper_wide">
			<a href="index.html" id="logo">Podcast.fm</a>
			<nav>
				<ul>
					<li><%= link_to "Explore", podcasts_path %></li>
					<li><%= link_to "Sign In", new_podcast_session_path %></li>
					<li><%= link_to "Create a Podcast", new_podcast_registration_path %></li>
				</ul>
			</nav>
		</div>
	</header>

	<div class="wrapper_skinny">
		<h1>Discover your new favorite<br>podcast, or create your own.</h1>
		<%= link_to "Create a Podcast", new_podcast_registration_path, class: 'button button_highlight' %>
		<%= link_to "Explore", podcasts_path, class: "button button_white" %>
	</div>
</div>